version: '2'

services:
    projen:
        build:
            context: .
            dockerfile: DockerfileJen
        ports:
            - "8080:8080"
    projir:
        build:
            context: .
            dockerfile: DockerfileJir
        ports:
            - "8081:8080"
    pronex:
        build: 
            context: .
            dockerfile: DockerfileNex
        ports:
            - "8082:8081"        
    prozab:
        build: 
            context: .
            dockerfile: DockerfileZab
        ports:
            - "8083:8080"
    proucd:
        build: 
            context: .
            dockerfile: DockerfileUCD
        ports:
            - "8084:8443"
